version: '3.3'

services:
 mariadb:
  container_name: mariadb
  build:
   context: requirements/mariadb/
   dockerfile: Dockerfile
  networks:
   - inception
  volumes:
   - mariadb_data:/var/lib/mysql
  secrets:
    - db_root_password
    - db_password
    - credentials
  ports:
   - "3306:3306"
  restart: always
  
 wordpress:
  container_name: wordpress
  build:
   context: requirements/wordpress
   dockerfile: Dockerfile
  networks:
   - inception
  depends_on:
   - mariadb
  volumes:
   - wordpress_data:/var/www/html/
  env_file: .env
  secrets:
    - credentials
    - db_password
    - wp_admin_pass
    - wp_user_pass
  ports:
   - "9000:9000"
  restart: always

 nginx:
  container_name: nginx
  build:
   context: requirements/nginx
   dockerfile: Dockerfile
  networks:
   - inception
  depends_on:
   - wordpress
  volumes:
   - wordpress_data:/var/www/html/
  env_file: .env
  ports:
   - "443:443" 
  restart: always

secrets:
  credentials:
    file: ../secrets/credentials.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_pass:
    file: ../secrets/wp_admin_pass.txt
  wp_user_pass:
    file: ../secrets/wp_user_pass.txt


volumes:
 mariadb_data:
  driver: local
  driver_opts:
   type: 'none'
   o: 'bind'
   device: /home/mkerkeni/data/mariadb
 wordpress_data:
  driver: local
  driver_opts:
   type: 'none'
   o: 'bind'
   device: /home/mkerkeni/data/wordpress
  
networks:
 inception:
  driver: bridge
